module.exports = Object.freeze({
  DAMAGE: 5,
  PLAYER_RADIUS: 20,
  PLAYER_MAX_HP: 100,
  PLAYER_SPEED: 300,  //400
  PLAYER_ACCELERATION: 2000,
  PLAYER_FIRE_COOLDOWN: 0.45, //0.15

  BULLET_RADIUS: 8, //8
  BULLET_SPEED: 1600, //800
  BULLET_HP: 10,

  ASTEROID_HP: 30,
  ASTEROID_MIN_RADIUS: 10,
  ASTEROID_MAX_RADIUS: 30,

  SCORE_BULLET_HIT: 20,
  SCORE_PER_SECOND: 1,

  MAP_SIZE: 2000,
  VISION_RANGE: 2000,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    INPUT: 'input',
    DIRECTION: 'direction',
    GAME_OVER: 'dead',
  },
});
